name: CI

on:
  pull_request:
  push:
    branches: [main, dev]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Enable Corepack
        run: | 
          corepack enable
          corepack install

      - name: Install deps
        run: yarn install --immutable

      - name: Run tests
        run: yarn test
